#!/bin/bash
# deps: jq, curl

invcfg=""$HOME"/.config/inv/inv.conf"
source $invcfg
type="0"
declare -a types
declare -a titles
declare -a videoids
declare -a authors

getdata () {
    while read -r line; do
        types+=("$line")
    done < <(echo "$1" | jq -r '.[].type')
    while read -r line; do
        titles+=("$line")
    done < <(echo "$1" | jq -r '.[].title')
    while read -r line; do
        videoids+=("$line")
    done < <(echo "$1" | jq -r '.[].videoId')
    while read -r line; do
        authors+=("$line")
    done < <(echo "$1" | jq -r '.[].author')
}

printresults () {
    for ((i=1; i<${#videoids[@]}; i++)); do
        if [[ "${types[$i]}" -eq "video" ]] || [[ "${types[$i]}" -eq "shortVideo" ]]; then
            printresult "$i"
        fi
    done
}

printresult () {
        printf "\033[1;37m"$i") %s\033[0m \033[0;34m[%s]\033[0m\n\t\033[0;35mhttps://%s/watch?v=%s\033[0m\n\n" "${titles[$1]}" "${authors[$1]}" "$instance" "${videoids[$1]}"
}

prepareresults () {
    echo "$(echo "$@" | sed "s/\s/+/g")"
}

isnum () {
    case "$1" in
        *[!0-9]*|"") return 1;;
        *) return 0;;
    esac
}

getjsondata () {
    case "$type" in
        search) curl -s https://"$instance"/api/v1/search?q="$1" ;;
        popular) curl -s https://"$instance"/api/v1/popular ;;
        trending) curl -s https://"$instance"/api/v1/trending ;;
    esac
}

getvideos () {
    string=$(prepareresults "$@")
    printf "Getting video data...\n"
    jsondata=$(getjsondata $string)
    getdata "$jsondata"
    printresults
    printf "Open in %s? (number or blank to exit) " "$player"
    read answer
    if isnum "$answer" && [[ "$answer" -le "${#videoids[@]}" ]]; then
        i=$(((answer--)))
        "$player" https://"$instance"/watch?v=${videoids[i]}
    else
        printf "Exiting.\n"
    fi
}

usage () {
    echo "inv <options> <query>
    Options:
    --help, -h                  Show usage
    --search, -s                Search videos (default option)
    --popular, -p               View popular videos on instance
    --trending, -t              View trending videos"
}

case "$1" in
    --help | -h) usage ;;
    --popular | -p) type="popular" && getvideos ${@:2} ;;
    --trending | -t) type="trending" && getvideos ${@:2} ;;
    --search | -s) type="search" && getvideos ${@:2} ;;
    * ) type="search" && getvideos "$@" ;;
esac
