#!/bin/bash
# deps: jq, curl

instance=vid.priv.au
player="mpv"
declare -a types
declare -a titles
declare -a videoids
declare -a authors

getdata () {
    while read -r line; do
        types+=("$line")
    done < <(echo "$1" | jq -r '.[].type')
    while read -r line; do
        titles+=("$line")
    done < <(echo "$1" | jq -r '.[].title')
    while read -r line; do
        videoids+=("$line")
    done < <(echo "$1" | jq -r '.[].videoId')
    while read -r line; do
        authors+=("$line")
    done < <(echo "$1" | jq -r '.[].author')
}

printresults () {
    for ((i=1; i<${#videoids[@]}; i++)); do
        if [[ "${types[$i]}" -eq "video" ]]; then
            printresult "$i"
        fi
    done
}

printresult () {
        printf "\033[1;37m"$i") %s\033[0m \033[0;34m[%s]\033[0m\n\t\033[0;35mhttps://%s/watch?v=%s\033[0m\n\n" "${titles[$1]}" "${authors[$1]}" "$instance" "${videoids[$1]}"
}

prepareresults () {
    echo "$(echo "$@" | sed "s/\s/+/g")"
}

isnum () {
    case "$1" in
        *[!0-9]*|"") return 1;;
        *) return 0;;
    esac
}

search () {
    string=$(prepareresults "$@")
    printf "Getting video data...\n"
    jsondata=$(curl -s https://"$instance"/api/v1/search?q="$string")
    getdata "$jsondata"
    printresults
    printf "Open in %s? (number or blank to exit) " "$player"
    read answer
    if isnum "$answer" && [[ "$answer" -le "${#videoids[@]}" ]]; then
        i=$(((answer--)))
        "$player" https://"$instance"/watch?v=${videoids[i]}
    else
        printf "Exiting.\n"
    fi
}

search "$@"
