#!/bin/bash
# deps: jq, curl

instance=vid.priv.au
declare -a types
declare -a titles
declare -a videoids
declare -a authors

gettypes () {
    while read -r line; do
        types+=("$line")
    done < <(echo "$1" | jq -r '.[].type')
}

gettitles () {
    while read -r line; do
        titles+=("$line")
    done < <(echo "$1" | jq -r '.[].title')
}

getvideoids () {
    while read -r line; do
        videoids+=("$line")
    done < <(echo "$1" | jq -r '.[].videoId')
}

getauthors () {
    while read -r line; do
        authors+=("$line")
    done < <(echo "$1" | jq -r '.[].author')
}

printresults () {
    for ((i=0; i<${#videoids[@]}; i++)); do
        if [[ "${types[$i]}" -eq "video" ]]; then
            printresult "$i"
        fi
    done
}

printresult () {
        printf "\033[1;37m"$i") %s\033[0m \033[0;34m[%s]\033[0m\n\t\033[0;35mhttps://%s/watch?v=%s\033[0m\n\n" "${titles[$1]}" "${authors[$1]}" "$instance" "${videoids[$1]}"
}

prepareresults () {
    echo "$(echo "$@" | sed "s/\s/+/g")"
}

search () {
    string=$(prepareresults "$@")
    printf "Getting video data...\n"
    jsondata=$(curl -s https://"$instance"/api/v1/search?q="$string")
    getvideoids "$jsondata"
    gettitles "$jsondata"
    getauthors "$jsondata"
    gettypes "$jsondata"
    printresults 
}

search "$@"
